const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('file:///'+path.resolve('dist/index.html').replaceAll('\\','/'));
 await p.evaluate(()=>{state=freshState();state.started=true;state.bag=Array.from({length:12},()=>makeItem(24));const mystery=makeItem(4);mystery.unknown=true;state.bag.push(mystery);setScreen('work','sort');
  window.flightDurations=[];const original=Element.prototype.animate;Element.prototype.animate=function(frames,options){if(this.classList.contains('flying-loot'))flightDurations.push(options.duration);return original.call(this,frames,options);};
 });
 const before=await p.evaluate(()=>({gold:state.gold,uids:owned().map(x=>x.uid).sort((a,b)=>a-b)}));
 assert.doesNotMatch(await p.locator('#autoSortButton').textContent(),/реклам/);
 await p.locator('#autoSortButton').click();
 assert.equal(await p.locator('#modal').isVisible(),false);
 await p.waitForFunction(()=>state.autoSorting&&document.querySelector('.flying-loot'));
 await p.evaluate(()=>{autoSort();});
 await p.waitForFunction(()=>state.stock.length>0&&state.bag.length>1);
 await p.waitForFunction(()=>!state.autoSorting,null,{timeout:10000});
 assert.deepEqual(await p.evaluate(()=>({gold:state.gold,uids:owned().map(x=>x.uid).sort((a,b)=>a-b)})),before);
 assert.equal(await p.evaluate(()=>state.stock.length),12);assert.equal(await p.evaluate(()=>state.bag.length),1);
 assert.equal(await p.evaluate(()=>isUnknown(state.bag[0])),true);
 assert.equal(await p.evaluate(()=>state.stock.every(x=>items[x.type].cat===3)),true);
 const durations=await p.evaluate(()=>flightDurations);assert.equal(durations.length,12);assert.ok(durations.every(d=>d>=162.5&&d<=212.5));
 assert.equal(await p.locator('.flying-loot').count(),0);assert.equal(await p.locator('#game header').evaluate(n=>n.inert),false);
 // Opening upgrades early must not consume the reminder after day one.
 await p.locator('#upgradesNav').click();await p.locator('#closeModal').click();
 assert.equal(await p.locator('#upgradesNav').evaluate(n=>n.classList.contains('upgrade-prompt')),false);
 await p.evaluate(()=>{state.bag=[];endDay('none');});
 assert.equal(await p.locator('#upgradesNav').evaluate(n=>n.classList.contains('upgrade-prompt')),true);
 await p.locator('#nextDay').click();assert.equal(await p.evaluate(()=>state.day),2);
 await p.screenshot({path:'audit_source/day-two-upgrades.png'});
 await p.reload();await p.locator('#loadGame').click();
 assert.equal(await p.locator('#upgradesNav').evaluate(n=>n.classList.contains('upgrade-prompt')),true);
 await p.locator('#upgradesNav').click();assert.equal(await p.locator('#upgradesNav').evaluate(n=>n.classList.contains('upgrade-prompt')),false);
 await p.locator('#closeModal').click();await p.reload();await p.locator('#loadGame').click();
 assert.equal(await p.locator('#upgradesNav').evaluate(n=>n.classList.contains('upgrade-prompt')),false);
 assert.deepEqual(errors,[]);console.log('PASS: direct free autosort, sequential flights at twice the speed, no duplicates/loss, unknown remains, day-one upgrade prompt persists and dismisses on opening');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
