const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1280,height:800},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.resolve('dist/index.html').replaceAll('\\','/'));
 await p.locator('#startGame').click();await p.waitForFunction(()=>document.getElementById('buyBag')?.textContent==='Отсортировать');
 assert.equal(await p.evaluate(()=>state.offers.length),1);assert.equal(await p.locator('#visitor').isVisible(),true);assert.equal(await p.locator('#tutorialGuide').count(),1);await p.screenshot({path:'audit_source/tutorial-bag.png'});
 await p.locator('#buyBag').click();assert.equal(await p.evaluate(()=>state.gold),80);assert.equal(await p.evaluate(()=>state.bag.length),4);
 await p.waitForFunction(()=>state.tutorial.stage==='sort');await p.waitForTimeout(300);
 const known=await p.evaluate(()=>state.bag.filter(x=>!isUnknown(x)).map(x=>({uid:x.uid,cat:items[x.type].cat})));assert.deepEqual(known.map(x=>x.cat),[3,4,0]);
 for(const x of known){await p.locator(`#pile [data-uid="${x.uid}"]`).click();await p.waitForTimeout(100);assert.match(await p.locator('.tutorial-note span').textContent(),/Положите/);await p.locator(`#shelves [data-cat="${x.cat}"]`).click();}
 assert.equal(await p.evaluate(()=>state.seconds),180);await p.screenshot({path:'audit_source/tutorial-unknown.png'});
 await p.reload();await p.locator('#loadGame').click();assert.equal(await p.evaluate(()=>state.tutorial.active),true);assert.equal(await p.evaluate(()=>state.bag.length),1);
 await p.locator('#pile .mystery-item').click();await p.locator('#heldRecognize').click();await p.locator('#inspectUnknown').click();await p.waitForFunction(()=>document.querySelector('#tutorialGuide.cleaning'));await p.screenshot({path:'audit_source/tutorial-cleaning.png'});
 await p.evaluate(()=>{for(let i=0;i<80&&!document.getElementById('cleanKey').disabled;i++)document.getElementById('cleanKey').click();});
 await p.waitForFunction(()=>document.querySelector('.tutorial-note span').textContent.includes('Закройте'));await p.locator('#closeModal').click();
 const last=await p.evaluate(()=>({uid:state.bag[0].uid,cat:items[state.bag[0].type].cat}));await p.locator(`#pile [data-uid="${last.uid}"]`).click();await p.locator(`#shelves [data-cat="${last.cat}"]`).click();
 await p.waitForFunction(()=>state.tutorial.stage==='guest');await p.locator('#arrivalSignal').click();await p.waitForFunction(()=>document.getElementById('receptionOrder')?.textContent==='Собрать посылку');await p.locator('#receptionOrder').click();
 await p.waitForFunction(()=>document.getElementById('acceptOrder')?.textContent==='Собрать посылку');await p.locator('#acceptOrder').click();await p.waitForFunction(()=>state.tutorial.stage==='assembly'&&state.mode==='order');
 const first=await p.evaluate(()=>({type:state.order.recipe[0].type,cat:items[state.order.recipe[0].type].cat}));await p.locator(`#shelves [data-cat="${first.cat}"]`).click();await p.screenshot({path:'audit_source/tutorial-assembly.png'});
 const uid=await p.evaluate(type=>state.stock.find(x=>x.type===type).uid,first.type);await p.locator(`#sourceItems [data-uid="${uid}"]`).click();await p.locator('#parcelDrop').click();await p.waitForFunction(()=>!state.tutorial.active);
 assert.equal(await p.locator('#tutorialGuide').count(),0);assert.equal(await p.evaluate(()=>state.order.packed.length),1);assert.equal(await p.evaluate(()=>localStorage.getItem(TUTORIAL_KEY)),'1');
 await p.evaluate(()=>startGame());assert.equal(await p.evaluate(()=>!!state.tutorial?.active),false);
 assert.equal(await p.evaluate(()=>state.offers.length),1);
 await p.locator('#settings').click();assert.equal(await p.evaluate(()=>state.paused),true);
 await p.locator('#resetLevel').click();await p.waitForFunction(()=>state.tutorial?.active&&document.getElementById('buyBag')?.textContent==='Отсортировать');
 assert.equal(await p.evaluate(()=>state.day),1);assert.equal(await p.evaluate(()=>state.gold),80);assert.equal(await p.evaluate(()=>state.stock.length),0);
 await p.locator('#buyBag').click();await p.locator('#settings').click();await p.waitForFunction(()=>!document.getElementById('tutorialGuide'));
 await p.locator('#resumeSettings').click();await p.waitForFunction(()=>document.getElementById('tutorialGuide'));
 assert.equal(await p.evaluate(()=>state.screen),'work');assert.equal(await p.evaluate(()=>state.bag.length),4);
 await p.screenshot({path:'audit_source/tutorial-settings-work.png'});
 await p.locator('#settings').click();await p.screenshot({path:'audit_source/tutorial-settings.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: instant free tutorial bag, helmet/ingredient/trophy steps, frozen clock, saved tutorial, unknown cleaning and close, guest/order/packing sequence, one-time completion');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
