'use strict';
let dragItem=null,heldItem=null,suppressClickUntil=0;
function orderNeeds(){if(!modal)return [];return modal.type==='cook'?RECIPES[guests.find(g=>g.id===modal.guest).recipe].need:[4,4,5,1,6];}
function assemblyReady(){const need=orderNeeds();return need.length===modal.selected.length&&need.every(i=>modal.selected.filter(v=>v===i).length===need.filter(v=>v===i).length);}
function assemblySlots(){const need=orderNeeds();return [...new Set(need)].map(i=>{const target=need.filter(v=>v===i).length,count=modal.selected.filter(v=>v===i).length;return `<div class="required-slot ${count===target?'filled':''}" data-slot="${i}" role="button" tabindex="0" aria-label="Положить ${ING[i][0]}, ${count} из ${target}">${artIcon(ingredientArt[i],48)}<span><strong>${ING[i][0]}</strong><small>${count===target?'Готово':count?'Добавьте ещё':'Перетащите сюда'}</small></span><span class="slot-count">${count}/${target}</span>${count?`<button class="remove-item" data-remove="${i}" aria-label="Вернуть ${ING[i][0]} на склад">↶</button>`:''}</div>`;}).join('');}
function assemblyPantry(options){return options.map(i=>{const n=state.stock[i]-modal.selected.filter(v=>v===i).length;return `<button class="ingredient-card ${heldItem===i?'picked':''}" data-drag-item="${i}" aria-label="Взять ${ING[i][0]}" ${n<=0?'disabled':''}>${artIcon(ingredientArt[i],64)}<strong>${ING[i][0]}</strong><small>В запасе: ${n}</small></button>`;}).join('');}
function assemblyUI(title,label,options,actionName,actionText){show(modalHead(label,title)+`<p>Перетащите предмет со склада в его ячейку. Или возьмите кликом и нажмите на ячейку.</p><div class="assembly"><div class="assembly-zone" id="dropzone"><div class="zone-title"><span>${label==='Кухня'?'ПЛИТА · ПОЛОЖИТЕ ИНГРЕДИЕНТЫ':'СЮДА НУЖНО ПОЛОЖИТЬ'}</span><b id="placed-count">${modal.selected.length} / ${orderNeeds().length}</b></div><div class="required-list" id="required-list">${assemblySlots()}</div></div><div><div class="pantry-title">${label==='Кухня'?'Продукты на полке':'Припасы на складе'}</div><div class="pantry" id="pantry">${assemblyPantry(options)}</div></div></div><div class="assembly-foot"><span class="hint" id="assemblyHint">Иконки показывают состав заказа. Стрелка ↶ возвращает предмет на полку.</span><button class="primary" data-action="${actionName}" id="assemblySubmit" ${assemblyReady()?'':'disabled'}>${actionText}</button></div>`);modal.options=options;}
function cookUI(){const g=guests.find(g=>g.id===modal.guest),r=RECIPES[g.recipe];if(modal.step===0){const options=[...new Set([...r.need,0,1,2,3,11,7])].slice(0,6).sort((a,b)=>a-b);assemblyUI(r.name,'Кухня',options,'cook','Готовить');}else show(modalHead('Кухня',r.name)+`<div class="board heat-board simmer">${r.need.map(i=>artIcon(ingredientArt[i],65)).join(' + ')}<span>→</span>${artIcon('pot',115)}</div><h3 class="cooking-title">Блюдо готовится…</h3><p>Когда полоска заполнится, официант автоматически подаст заказ.</p><div class="cook-progress" id="cookProgress" role="progressbar" aria-label="Приготовление блюда" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="cookFill"></i></div><p class="cook-time" id="cookTime">${Math.ceil(modal.duration)} с</p><p class="hint">Можно отменить приготовление, закрыв окно. Ингредиенты вернутся на склад.</p>`);}
function startCooking(){if(modal?.type!=='cook'||modal.step!==0)return;if(!assemblyReady()){toast('Положите все ингредиенты на плиту');return;}const r=RECIPES[guests.find(g=>g.id===modal.guest).recipe];if(r.need.some(i=>state.stock[i]<1)){toast('Не хватает продуктов');return;}cancelCarry();modal.step=1;modal.elapsed=0;modal.duration=5/(1+state.up.kitchen*.22);cookUI();}
function advanceCooking(dt){if(modal?.type!=='cook'||modal.step!==1)return;modal.elapsed=Math.min(modal.duration,modal.elapsed+dt);const percent=Math.round(modal.elapsed/modal.duration*100);$('cookFill').style.width=percent+'%';$('cookProgress').setAttribute('aria-valuenow',percent);$('cookTime').textContent=Math.max(0,Math.ceil(modal.duration-modal.elapsed))+' с';if(modal.elapsed<modal.duration)return;const g=guests.find(g=>g.id===modal.guest);if(g?.phase==='seated'){RECIPES[g.recipe].need.forEach(i=>state.stock[i]--);finishGuest(g,true,1);}closeModal();}
function supplyUI(){assemblyUI('Соберите набор в поход','Склад',[4,5,1,6,0,11],'pack','Передать герою · 58 золота');}
function trophyUI(){show(modalHead('Разделочный стол','Трофей пещерного краба')+`<div class="board heat-board">${artIcon('crab_leg',150)}</div><div class="trophy-contents"><span>${artIcon('meat',43)}Мясо</span><span>${artIcon('scales',43)}Панцирь</span><span>${artIcon('slime',43)}Ингредиент</span></div><p>Сделайте три надреза в зелёной зоне. Точность увеличивает добычу и награду.</p><div class="timing"><div class="zone"></div><div class="needle" id="needle"></div></div><p id="cutStatus">Надрезы: ${modal.tries} / 3 · точных: ${modal.hits}</p><button class="primary" data-action="cut">Сделать надрез</button>`);}
function refreshAssembly(){if(!modal?.options)return;$('required-list').innerHTML=assemblySlots();$('pantry').innerHTML=assemblyPantry(modal.options);$('placed-count').textContent=modal.selected.length+' / '+orderNeeds().length;$('assemblySubmit').disabled=!assemblyReady();$('assemblyHint').textContent=assemblyReady()?(modal.type==='cook'?'Всё на плите. Нажмите «Готовить».':'Всё на месте. Заказ можно передать.'):heldItem===null?'Перетащите следующий предмет. Стрелка ↶ возвращает его на полку.':`В руках: ${ING[heldItem][0]}. Нажмите на нужную ячейку.`;}
function acceptItem(i,slot=null){if(!modal||!['cook','supply'].includes(modal.type)||modal.step!==0)return false;const need=orderNeeds(),count=modal.selected.filter(v=>v===i).length,required=need.filter(v=>v===i).length;if(slot!==null&&slot!==i){toast('У этого предмета другая ячейка');return false;}if(!required){toast('Этот предмет не нужен в заказе');return false;}if(count>=required){toast('Этого предмета уже достаточно');return false;}if(count>=state.stock[i]){toast('На складе больше нет этого предмета');return false;}modal.selected.push(i);heldItem=null;refreshAssembly();return true;}
function removeItem(i){const n=modal?.selected.indexOf(i);if(n>=0){modal.selected.splice(n,1);refreshAssembly();}}
function cancelCarry(){dragItem?.ghost?.remove();dragItem=null;heldItem=null;document.querySelector('.assembly-zone')?.classList.remove('over');}
function animateTransfer(i,x,y){const target=document.querySelector(`[data-slot="${i}"]`);if(!target)return;const r=target.getBoundingClientRect(),flight=document.createElement('div');flight.className='transfer-flight';flight.innerHTML=artIcon(ingredientArt[i],55);flight.style.left=(x-27)+'px';flight.style.top=(y-27)+'px';document.body.append(flight);requestAnimationFrame(()=>{flight.style.transform=`translate(${r.x+r.width/2-x}px,${r.y+r.height/2-y}px) scale(.6)`;flight.style.opacity='.3';});setTimeout(()=>flight.remove(),350);}
document.addEventListener('pointerdown',e=>{suppressClickUntil=0;const card=e.target.closest('[data-drag-item]');if(!card||card.disabled||e.button!==0)return;dragItem={i:+card.dataset.dragItem,x:e.clientX,y:e.clientY,pointer:e.pointerId,card,ghost:null};card.setPointerCapture?.(e.pointerId);});
document.addEventListener('pointermove',e=>{if(!dragItem||dragItem.pointer!==e.pointerId)return;const d=dragItem;if(!d.ghost&&Math.hypot(e.clientX-d.x,e.clientY-d.y)<5)return;e.preventDefault();if(!d.ghost){d.ghost=document.createElement('div');d.ghost.className='drag-ghost';d.ghost.innerHTML=artIcon(ingredientArt[d.i],72);document.body.append(d.ghost);}d.ghost.style.left=e.clientX+'px';d.ghost.style.top=e.clientY+'px';const target=document.elementFromPoint(e.clientX,e.clientY);$('dropzone')?.classList.toggle('over',!!target?.closest('#dropzone'));},{passive:false});
document.addEventListener('pointerup',e=>{if(!dragItem||dragItem.pointer!==e.pointerId)return;const d=dragItem;dragItem=null;d.card.releasePointerCapture?.(e.pointerId);if(!d.ghost)return;suppressClickUntil=performance.now()+400;d.ghost.remove();$('dropzone')?.classList.remove('over');const target=document.elementFromPoint(e.clientX,e.clientY),zone=target?.closest('#dropzone'),slot=target?.closest('[data-slot]');if(zone&&acceptItem(d.i,slot?+slot.dataset.slot:null))animateTransfer(d.i,e.clientX,e.clientY);});
document.addEventListener('pointercancel',cancelCarry);
document.addEventListener('click',e=>{if(performance.now()<suppressClickUntil)return;const card=e.target.closest('[data-drag-item]'),remove=e.target.closest('[data-remove]'),slot=e.target.closest('[data-slot]');if(remove){removeItem(+remove.dataset.remove);return;}if(card&&!card.disabled){heldItem=heldItem===+card.dataset.dragItem?null:+card.dataset.dragItem;refreshAssembly();$('assemblyHint').textContent=heldItem===null?'Предмет отпущен.':`В руках: ${ING[heldItem][0]}. Нажмите на нужную ячейку.`;return;}if(slot&&heldItem!==null){const i=heldItem;if(acceptItem(i,+slot.dataset.slot))animateTransfer(i,e.clientX,e.clientY);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')cancelCarry();const slot=e.target.closest?.('[data-slot]');if(slot&&heldItem!==null&&['Enter',' '].includes(e.key)){e.preventDefault();acceptItem(heldItem,+slot.dataset.slot);}});
