function dashboardContent(tab){let html='';
if(tab==='upgrades')html='<div class="cards">'+UPGRADES.map((u,i)=>{const lv=state.up[u.key],cost=Math.round(u.base*Math.pow(1.8,lv));return `<article class="upgrade"><h3>${u.name}<span class="level">${lv} / ${u.max}</span></h3><span class="upgrade-art">${artIcon(['workbench','forge','shelves','innkeeper','trophy_cabinet'][i],35)}</span><p>${u.desc}</p><button data-up="${u.key}" ${lv>=u.max||state.gold<cost?'disabled':''}>${lv>=u.max?'Максимальный уровень':`Улучшить · ${cost} ◈`}</button></article>`;}).join('')+'</div>';
if(tab==='stock')html='<div class="inventory">'+ING.map((i,n)=>`<div class="item">${artIcon(ingredientArt[n],30)}<span>${i[0]}</span><b>${state.stock[n]}</b></div>`).join('')+`</div><div class="stock-help"><span class="hint">Бесплатная доставка каждые 24 игровые секунды.</span><button class="small" data-action="buy-stock" ${state.gold<25?'disabled':''}>Пополнить всё · 25 ◈</button></div>`;
if(tab==='recipes')html='<div class="recipes">'+RECIPES.map(r=>`<div class="recipe" style="opacity:${r.rep<=state.rep?1:.45}">${artIcon(ingredientArt[r.need[0]],34)}<span>${r.name}<small>${r.need.map(i=>ING[i][0]).join(' + ')} · ${r.value} ◈</small><small>${r.rep<=state.rep?'Рецепт открыт':'Нужно '+r.rep+' репутации'}</small></span></div>`).join('')+'</div>';
if(tab==='staff')html=`<div class="cards" style="grid-template-columns:repeat(2,1fr)"><article class="upgrade"><h3>Бруна · повар</h3><span class="upgrade-art">${artIcon('butcher',70)}</span><p>Готовит простые блюда автоматически. Уровень кухни: ${state.up.kitchen}. Ускорение: ${state.up.kitchen*22}%.</p></article><article class="upgrade"><h3>Финн · трактирщик</h3><span class="upgrade-art">${artIcon('innkeeper',70)}</span><p>Принимает простые заказы и собирает оплату. Уровень: ${state.up.staff}. Базовый чек: ${12+state.up.staff*3} золота.</p></article></div>`;
return html;}
function renderTab(){const html=dashboardContent(tab);if($('tabContent').innerHTML!==html)$('tabContent').innerHTML=html;}
function openPanel(panel){if(!['stock','recipes'].includes(panel))return;modal={type:'panel',panel};show(`<button class="close" data-action="close" aria-label="Закрыть">×</button><div class="eyebrow">Таверна у подземелья</div><h2 id="modalTitle">${panel==='stock'?'Склад':'Книга рецептов'}</h2><p>${panel==='stock'?'Все припасы вашей таверны.':'Состав блюд, награды и условия открытия.'}</p><div class="collection-panel" id="collectionPanel"></div>`);refreshPanel();}
function refreshPanel(){if(modal?.type==='panel')$('collectionPanel').innerHTML=dashboardContent(modal.panel);}
function renderOrders(){const orders=guests.filter(g=>g.phase==='seated'&&g.kind!=='simple');$('orderCount').textContent=orders.length;const html=orders.length?orders.map(g=>`<button class="order ${g.wait<25?'urgent':''}" data-order="${g.id}"><span class="avatar">${artIcon(g.art||guestArt[g.type],58)}</span><span class="order-copy"><strong>${g.kind==='cook'?RECIPES[g.recipe].name:g.kind==='supply'?'Припасы в поход':'Разобрать трофей'}</strong><small>${g.name} · ${Math.ceil(g.wait)} с</small><span class="order-call">Выполнить заказ →</span></span><span class="reward">${g.kind==='cook'?RECIPES[g.recipe].value:g.kind==='supply'?58:52} ◈</span></button>`).join(''):'<div class="empty">Скоро здесь появятся заказы.<br>Гости уже идут в таверну.</div>';if($('orders').innerHTML!==html)$('orders').innerHTML=html;}
