'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
const KEY='monster-tavern-v1';
const ING=[['Мука','🍞'],['Мясо','🥩'],['Грибы','🍄'],['Эль','🍺'],['Зелье','🧪'],['Фонарь','🔥'],['Верёвка','🪢'],['Лапа краба','🦀'],['Слизь','💧'],['Ягоды','🫐'],['Рёбра','🦴'],['Травы','🌿']];
const RECIPES=[{name:'Хлеб из печи',need:[0,11],rep:0,value:30},{name:'Грибная похлёбка',need:[2,11],rep:0,value:38},{name:'Жаркое охотника',need:[1,2],rep:0,value:42},{name:'Грибной эль',need:[2,3],rep:0,value:35},{name:'Лапа пещерного краба',need:[7,3],rep:10,value:65},{name:'Суп из слизня',need:[8,11],rep:20,value:75},{name:'Десерт из светящихся ягод',need:[9,0],rep:35,value:85},{name:'Драконьи рёбра',need:[10,11],rep:50,value:110}];
const UPGRADES=[{key:'hall',name:'Столики в зале',icon:'▦',desc:'Ещё один стол и больше гостей.',base:85,max:3},{key:'kitchen',name:'Кухня',icon:'♨',desc:'Повар на 22% быстрее за уровень.',base:100,max:3},{key:'storage',name:'Склад',icon:'▤',desc:'Больше запасов в бесплатной доставке.',base:80,max:3},{key:'staff',name:'Обучение официанта',icon:'♟',desc:'Обслуживание быстрее, выручка выше.',base:110,max:3},{key:'decor',name:'Трофеи и уют',icon:'✧',desc:'Чек всех заказов выше на 15%.',base:90,max:3}];
const seats=[{x:385,y:285},{x:565,y:285},{x:385,y:445},{x:565,y:445},{x:745,y:285},{x:745,y:445}];
function fresh(){return {gold:120,rep:0,served:0,earned:0,activeDone:0,time:0,stock:Array(12).fill(6),up:{hall:0,kitchen:0,storage:0,staff:0,decor:0},quest:0,event:{next:90,active:false,left:0,done:0,target:5},log:['Огонь разожжён. Первый гость уже в пути.']};}
let state=fresh(),resumed=false;
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&s.version===1&&Number.isFinite(s.gold)&&s.stock?.length===12&&s.up&&s.event){state={...fresh(),...s};resumed=true;}}catch{}
let guests=[],particles=[],nextGuest=2,nextId=1,spawnCount=0,paused=false,speed=1,tab='upgrades',modal=null,toastTimer=0,uiTimer=0,saveTimer=0,deliveryTimer=0,frameTime=0,previousFocus=null;
function log(t){state.log.unshift(t);state.log=state.log.slice(0,5);}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
function save(){try{localStorage.setItem(KEY,JSON.stringify({...state,version:1}));$('saveStatus').textContent='Прогресс сохранён · всё работает офлайн';}catch{$('saveStatus').textContent='Браузер запретил сохранение · текущая игра работает';}}
function show(content){if($('overlay').hidden)previousFocus=document.activeElement;$('modal').innerHTML=content;$('overlay').hidden=false;queueMicrotask(()=> $('modal').querySelector('button:not(:disabled)')?.focus());}
function closeModal(){cancelCarry();modal=null;$('overlay').hidden=true;previousFocus?.focus?.();renderUI();save();}
function intro(){modal={type:'help'};show(`<button class="close" data-action="close" aria-label="Закрыть">×</button><div class="eyebrow">Добро пожаловать, хозяин</div><h2 id="modalTitle">За дверью — подземелье.<br>Здесь — дом.</h2><p>Превратите маленькую таверну в любимое место авантюристов. Повар и официант уже на смене — простые заказы они выполнят сами.</p><div class="intro-steps"><div><b>01</b>Нажимайте на гостей с золотым <strong>!</strong></div><div><b>02</b>Перетаскивайте продукты в ячейки заказа</div><div><b>03</b>Вкладывайте доход в уют и автоматизацию</div></div><p class="hint">Цель первой сессии: обслужить рейдовую группу и заработать 50 репутации. Время останавливается в мини-играх и скрытой вкладке. Пробел — пауза.</p><button class="primary" data-action="close">${resumed?'Вернуться к таверне':'Открыть таверну'} →</button>`);}
function makeGuest(){const free=seats.slice(0,3+state.up.hall).map((_,i)=>i).filter(i=>!guests.some(g=>g.seat===i&&g.phase!=='leaving'));if(!free.length)return;const seat=free[Math.floor(Math.random()*free.length)],n=spawnCount++,kind=n%4===3?'simple':['cook','supply','trophy'][n%3],type=n%3;guests.push({id:nextId++,seat,x:939,y:573,phase:'entering',route:0,kind,type,art:guestArt[n%guestArt.length],name:['Новичок','Охотник','Маг'][type],wait:95,work:0,recipe:Math.floor(Math.random()*RECIPES.filter(r=>r.rep<=state.rep).length)});}
function earn(amount,rep=0,x=500,y=330){amount=Math.round(amount*(1+state.up.decor*.15));state.gold+=amount;state.earned+=amount;state.rep+=rep;particles.push({x,y,text:'+'+amount+' зол.',life:2});return amount;}
function finishGuest(g,active=true,quality=1){if(!g||g.phase==='leaving')return;const value=g.kind==='cook'?RECIPES[g.recipe].value:g.kind==='supply'?58:52;const reward=earn(active?value*quality:12+state.up.staff*3,active?Math.round(3*quality):1,g.x,g.y-35);state.served++;if(active)state.activeDone++;g.phase='leaving';g.route=0;g.work=0;if(state.event.active){state.event.done++;if(state.event.done>=state.event.target){state.event.active=false;state.event.next=state.time+180;earn(180,10,740,180);log('Рейдовая группа довольна! +180 золота и 10 репутации.');toast('Пир удался! 180 золота и 10 репутации');}}if(active){log(g.name+': заказ выполнен, +'+reward+' золота.');toast('Заказ готов! +'+reward+' золота');}checkQuest();}
function checkQuest(){const goals=[{v:state.served,n:10,reward:100},{v:state.activeDone,n:6,reward:150},{v:state.rep,n:50,reward:250}];let q=goals[state.quest];if(q&&q.v>=q.n){state.gold+=q.reward;state.quest++;log('Цель выполнена! +'+q.reward+' золота.');toast('Новая веха! +'+q.reward+' золота');}}
function upgrade(key){const u=UPGRADES.find(u=>u.key===key);if(!u)return;const lv=state.up[key],cost=Math.round(u.base*Math.pow(1.8,lv));if(lv>=u.max||state.gold<cost)return;state.gold-=cost;state.up[key]++;log(u.name+': уровень '+state.up[key]+'.');toast('Улучшение построено: '+u.name);renderUI();save();}
function buyStock(){if(state.gold<25)return;state.gold-=25;state.stock=state.stock.map(n=>Math.min(30+state.up.storage*10,n+4+state.up.storage*2));toast('Доставка: припасы пополнены');renderUI();if(modal?.type==='panel'&&modal.panel==='stock')refreshPanel();save();}
function startEvent(){if(state.event.active||state.time<state.event.next)return;state.event={...state.event,active:true,left:70,done:0,target:5};nextGuest=0;log('Рейдовая группа у ворот! Обслужите 5 гостей за 70 секунд.');toast('Час пира! Обслужите 5 гостей');renderUI();}
function update(dt){state.time+=dt;nextGuest-=dt;if(nextGuest<=0){makeGuest();nextGuest=state.event.active?2:5;}deliveryTimer+=dt;if(deliveryTimer>=24){deliveryTimer=0;state.stock=state.stock.map(n=>Math.min(30+state.up.storage*10,n+2+state.up.storage));log('Кладовая пополнена бесплатной доставкой.');}if(state.event.active){state.event.left-=dt;if(state.event.left<=0){state.event.active=false;state.event.next=state.time+120;log('Пир окончен. Следующая группа даст новый шанс.');toast('Не всех успели обслужить — следующая группа придёт позже.');}}for(const g of guests){const s=seats[g.seat];if(g.phase==='entering'||g.phase==='leaving'){const route=g.phase==='entering'?[{x:883,y:541},{x:815,y:523},{x:s.x+63,y:523},{x:s.x+63,y:s.y+27}]:[{x:s.x+63,y:523},{x:815,y:523},{x:883,y:541},{x:1030,y:573}],target=route[g.route],dx=target.x-g.x,dy=target.y-g.y,d=Math.hypot(dx,dy),step=dt*105;if(d<=step){g.x=target.x;g.y=target.y;g.route++;if(g.route>=route.length){g.phase=g.phase==='entering'?'seated':'gone';}}else{g.x+=dx/d*step;g.y+=dy/d*step;}}else if(g.phase==='seated'){if(g.kind==='simple'){g.work+=dt*(1+state.up.kitchen*.22+state.up.staff*.18);if(g.work>=12)finishGuest(g,false);}else{g.wait-=dt;if(g.wait<=0){g.phase='leaving';g.route=0;state.rep=Math.max(0,state.rep-1);log(g.name+' не дождался особого заказа. −1 репутации.');}}}}guests=guests.filter(g=>g.phase!=='gone');saveTimer+=dt;if(saveTimer>=5){saveTimer=0;save();}}
function openOrder(id){const g=guests.find(g=>g.id===id);if(!g||g.phase!=='seated'||g.kind==='simple')return;modal={type:g.kind,guest:id,selected:[],step:0,meter:0,hits:0,tries:0};if(g.kind==='cook')cookUI();if(g.kind==='supply')supplyUI();if(g.kind==='trophy')trophyUI();}
function modalHead(label,title){return `<button class="close" data-action="close" aria-label="Отложить заказ">×</button><div class="eyebrow">${label} · время в таверне остановлено</div><h2 id="modalTitle">${title}</h2>`;}
function action(a){if(a==='close'){closeModal();return;}if(a==='cook'){startCooking();return;}if(a==='clearbag'){modal.selected=[];supplyUI();}if(a==='pack'){const need=[4,4,5,1,6],selected=[...modal.selected].sort().join();if(selected!==[...need].sort().join()){toast('Проверьте состав: 2 зелья, фонарь, мясо, верёвка');return;}for(const i of new Set(need)){if(state.stock[i]<need.filter(n=>n===i).length){toast('Не хватает припасов');return;}}need.forEach(i=>state.stock[i]--);finishGuest(guests.find(g=>g.id===modal.guest));closeModal();}if(a==='cut'){modal.tries++;if(modal.meter>=.38&&modal.meter<=.62)modal.hits++;if(modal.tries===3){state.stock[1]+=2;state.stock[7]+=1+modal.hits;state.stock[8]+=modal.hits;finishGuest(guests.find(g=>g.id===modal.guest),true,1+modal.hits*.15);log('Трофей разобран: мясо, краб и алхимические ингредиенты.');closeModal();}else{modal.meter=0;$('cutStatus').textContent=`Надрезы: ${modal.tries} / 3 · точных: ${modal.hits}`;}}if(a==='reset-confirm'){state=fresh();guests=[];particles=[];nextGuest=2;nextId=1;spawnCount=0;deliveryTimer=0;paused=false;speed=1;resumed=false;save();closeModal();intro();}}
function renderUI(){for(const k of ['gold','rep','served'])$(k).textContent=Math.floor(state[k]).toLocaleString('ru-RU');$('day').textContent=String(1+Math.floor(state.time/180)).padStart(2,'0');const minute=480+Math.floor(state.time%180/180*720);$('clock').textContent=String(Math.floor(minute/60)).padStart(2,'0')+':'+String(minute%60).padStart(2,'0')+' · У городских ворот';$('status').textContent=paused?'Таверна на паузе':'Таверна открыта';$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Продолжить игру':'Пауза');$('speed').textContent=speed+'×';renderOrders();const e=state.event,seconds=Math.max(0,Math.ceil(e.next-state.time));$('eventBtn').disabled=!e.active&&seconds>0||e.active;$('eventBtn').textContent=e.active?`${e.done} / ${e.target} гостей · осталось ${Math.ceil(e.left)} с`:seconds>0?`Группа прибудет через ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`:'Накрыть столы →';$('eventTitle').textContent=e.active?'Пир после победы':'Возвращение из рейда';$('eventText').textContent=e.active?'Обслужите 5 любых гостей за 70 секунд. Награда: 180 золота и 10 репутации.':'Герои спускаются за первым боссом. Скоро им понадобится настоящий пир.';const goals=[['Место, куда возвращаются','Обслужите 10 гостей · награда 100 золота',state.served,10],['Хозяин на все руки','Выполните 6 особых заказов · награда 150 золота',state.activeDone,6],['Легенда у городских ворот','Получите 50 репутации · награда 250 золота',state.rep,50]],q=goals[state.quest]||['Таверна стала легендой','Все цели выполнены. Продолжайте обустраивать свой уголок.',1,1];$('goalTitle').textContent=q[0];$('goalText').textContent=q[1];$('goalCount').textContent=Math.min(q[2],q[3])+' / '+q[3];$('goalFill').style.width=Math.min(100,q[2]/q[3]*100)+'%';$('stockTotal').textContent='· '+state.stock.reduce((a,b)=>a+b,0);renderTab();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}function label(text,x,y,color='#d7d7b4',size=12){ctx.font=`600 ${size}px "Segoe UI",sans-serif`;ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,x,y);}
function frame(now){const raw=Math.min((now-(frameTime||now))/1000,.08);frameTime=now;const running=!paused&&!modal&&!document.hidden;if(running)update(raw*speed);particles.forEach(p=>p.life-=raw);particles=particles.filter(p=>p.life>0);if(modal&&(modal.type==='trophy')&&!document.hidden){modal.meter=(modal.meter+raw*.65)%1;const n=$('needle');if(n)n.style.left=modal.meter*100+'%';}if(!document.hidden)advanceCooking(raw);drawScene(now/1000);uiTimer+=raw;if(uiTimer>.4){uiTimer=0;if(!modal)renderUI();}requestAnimationFrame(frame);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.order)openOrder(+b.dataset.order);if(b.dataset.up)upgrade(b.dataset.up);if(b.dataset.panel)openPanel(b.dataset.panel);if(b.dataset.tab){tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderTab();}if(b.dataset.ingredient!==undefined&&modal?.type==='cook'){const i=+b.dataset.ingredient,n=modal.selected.indexOf(i);if(n>=0)modal.selected.splice(n,1);else if(modal.selected.length<2)modal.selected.push(i);cookUI();}if(b.dataset.supply!==undefined&&modal?.type==='supply'){const i=+b.dataset.supply;if(modal.selected.length<5&&modal.selected.filter(v=>v===i).length<state.stock[i])modal.selected.push(i);supplyUI();}if(b.dataset.action==='buy-stock')buyStock();else if(b.dataset.action)action(b.dataset.action);});
$('pause').onclick=()=>{paused=!paused;renderUI();};$('speed').onclick=()=>{speed=speed===1?2:1;renderUI();};$('help').onclick=intro;$('eventBtn').onclick=startEvent;$('reset').onclick=()=>{modal={type:'reset'};show(modalHead('Новая история','Начать заново?')+'<p>Золото, улучшения и репутация этой таверны будут сброшены.</p><button class="primary" data-action="reset-confirm">Да, открыть новую таверну</button>');};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!modal&&e.target===document.body){e.preventDefault();paused=!paused;renderUI();}if(e.key==='Escape'&&modal)closeModal();if(e.key==='Tab'&&modal){const buttons=[...$('modal').querySelectorAll('button:not(:disabled)')];if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0]?.focus();}}});
canvas.addEventListener('click',e=>{if(modal||paused)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1000,y=(e.clientY-r.top)/r.height*680;const g=guests.find(g=>g.phase==='seated'&&g.kind!=='simple'&&Math.abs(x-g.x)<45&&y>g.y-125&&y<g.y+25);if(g){openOrder(g.id);return;}if(x<285&&y>365){openPanel('stock');}else if(x<285&&y<355){const g=guests.find(g=>g.kind==='cook'&&g.phase==='seated');if(g)openOrder(g.id);else toast('Повар готовит простые блюда. Особые заказы скоро появятся.');}});
window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Полный экран можно включить клавишей F11');}};
renderUI();if(!resumed)intro();requestAnimationFrame(frame);
