const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const elements=new Map(),saved=new Map();
function el(id){if(!elements.has(id))elements.set(id,{hidden:true,style:{},classList:{toggle(){}},setAttribute(){},addEventListener(){},querySelector(){return null;},querySelectorAll(){return [];},focus(){},getContext(){return {};}});return elements.get(id);}
const box={console,artIcon:()=>'',guestArt:['ranger','knight','mage'],ingredientArt:Array(12).fill('item'),document:{getElementById:el,querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},hidden:false},window:{addEventListener(){}},Image:class{},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},setTimeout:()=>0,clearTimeout(){},queueMicrotask(){},requestAnimationFrame(){}};
vm.createContext(box);
for(const file of ['assembly.js','dashboard.js','game.js'])vm.runInContext(fs.readFileSync(__dirname+'/'+file,'utf8'),box);
const run=code=>vm.runInContext(code,box);
const reset=()=>run('state=fresh();guests=[];modal=null;spawnCount=0;nextGuest=999;deliveryTimer=0;');
const guest=kind=>run(`guests=[{id:1,seat:0,x:448,y:312,phase:'seated',kind:'${kind}',name:'Тест',recipe:0,wait:95,work:0,route:0}];openOrder(1);`);
reset();run("upgrade('hall')");assert.equal(run('state.gold'),35);assert.equal(run('state.up.hall'),1);run("upgrade('hall')");assert.equal(run('state.gold'),35);
reset();guest('cook');run("modal.selected=[1,2];action('cook')");assert.equal(run('modal.step'),0);run("modal.selected=[0,11];action('cook');modal.meter=.5;action('serve')");assert.equal(run('state.gold'),165);assert.equal(run('state.stock[0]'),5);assert.equal(run('state.served'),1);assert.equal(run('state.rep'),5);
reset();guest('cook');run("modal.selected=[0,11];action('cook');closeModal()");assert.equal(run('state.stock[0]'),6);assert.equal(run('state.served'),0);
reset();guest('supply');run("modal.selected=[4,4,5,1,0];action('pack')");assert.equal(run('state.gold'),120);run("modal.selected=[4,4,5,1,6];action('pack')");assert.equal(run('state.gold'),178);assert.equal(run('state.stock[4]'),4);assert.equal(run('state.stock.reduce((a,b)=>a+b,0)'),67);
reset();guest('supply');assert.equal(run('acceptItem(0)'),false);assert.equal(run('acceptItem(4,5)'),false);assert.equal(run('acceptItem(4,4)'),true);assert.equal(run('acceptItem(4,4)'),true);assert.equal(run('acceptItem(4,4)'),false);assert.equal(run('state.stock[4]'),6);run('removeItem(4)');assert.equal(run('modal.selected.length'),1);run('closeModal()');assert.equal(run('state.stock[4]'),6);
reset();guest('cook');run('acceptItem(0,0);acceptItem(11,11)');assert.equal(run('assemblyReady()'),true);run("action('cook');modal.meter=.5;action('serve')");assert.equal(run('state.stock[0]'),5);
reset();guest('trophy');run("modal.meter=.5;action('cut');modal.meter=.5;action('cut');modal.meter=.5;action('cut')");assert.equal(run('state.served'),1);assert.equal(run('state.stock[7]'),10);assert.equal(run('state.stock[1]'),8);
reset();guest('simple');run('modal=null;for(let i=0;i<121;i++)update(.1)');assert.equal(run('state.served'),1);assert.equal(run('state.gold'),132);
reset();run('state.time=90;startEvent()');assert.equal(run('state.event.active'),true);run("for(let i=0;i<5;i++){let g={phase:'seated',kind:'simple',x:0,y:0};finishGuest(g,false);}");assert.equal(run('state.event.active'),false);assert.equal(run('state.gold'),360);assert.equal(run('state.rep'),15);
reset();run('state.time=90;startEvent();for(let i=0;i<701;i++)update(.1)');assert.equal(run('state.event.active'),false);assert.ok(run('state.event.next>state.time'));
reset();run("state.gold=99999;for(let i=0;i<5;i++)upgrade('hall')");assert.equal(run('state.up.hall'),3);assert.ok(run('seats.every(s=>s.x+87<844)'));
reset();run('nextGuest=0;for(let i=0;i<12000;i++)update(.1)');assert.ok(run('Number.isFinite(state.gold)&&state.gold>=0'));assert.ok(run('state.stock.every(n=>n>=0)'));assert.ok(run('guests.length<=8'));assert.ok(run('state.served>0'));
run('save()');const snapshot=JSON.parse(saved.values().next().value);assert.equal(snapshot.version,1);assert.equal(snapshot.gold,run('state.gold'));
console.log('PASS: upgrades, ingredients, cooking, cancellation, supply validation, trophy, automation, event success/failure, room bounds, 20-minute simulation, persistence.');
